services:
  - type: web
    name: birthday-reminder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_sqlite:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
